name: travel_aigent
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  stacked: ^3.4.0
  stacked_services: ^1.1.0
  stacked_themes: ^0.3.12
  dio: ^5.3.0
  logger: any
  flutter_dotenv: ^5.1.0
  hive: ^2.2.3
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.1
  firebase_analytics: ^10.4.4
  firebase_crashlytics: ^3.3.4
  cloud_firestore: ^4.8.4
  font_awesome_flutter: ^10.5.0
  simple_chips_input: ^1.1.0
  easy_autocomplete: ^1.6.0
  dart_countries: ^3.0.3
  dart_openai: ^3.0.0
  html: ^0.15.4
  beautiful_soup_dart: ^0.3.0
  flutter_svg: ^2.0.7
  percent_indicator: ^4.2.3
  intl: ^0.18.1
  calendar_date_picker2: ^0.5.2
  json_annotation: ^4.8.1
  separated_column: ^2.0.0
  email_validator: '^2.1.16'
  uuid: ^3.0.7
  fancy_password_field: ^2.0.0
  path_provider: ^2.1.0
  fuzzywuzzy: ^1.1.6
  equatable: ^2.0.5
  lottie: ^2.6.0
  animated_text_kit: ^4.2.1
  enum_to_string: ^2.0.1
  smooth_page_indicator: ^1.1.0
  cached_network_image: ^3.2.3
  provider: ^6.0.5
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.5
  flutter_lints: ^2.0.0
  surf_lint_rules: ^3.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svgs/
    - .env