// Mocks generated by Mockito 5.4.2 from annotations
// in travel_aigent/test/helpers/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;
import 'dart:ui' as _i12;

import 'package:beautiful_soup_dart/beautiful_soup.dart' as _i15;
import 'package:cloud_firestore/cloud_firestore.dart' as _i5;
import 'package:dart_openai/dart_openai.dart' as _i17;
import 'package:dio/dio.dart' as _i2;
import 'package:flutter/material.dart' as _i10;
import 'package:google_mobile_ads/google_mobile_ads.dart' as _i37;
import 'package:mockito/mockito.dart' as _i1;
import 'package:stacked_services/stacked_services.dart' as _i9;
import 'package:travel_aigent/models/airport_data_model.dart' as _i8;
import 'package:travel_aigent/models/destination_model.dart' as _i19;
import 'package:travel_aigent/models/duck_web_image_model.dart' as _i33;
import 'package:travel_aigent/models/exchange_rate_data_model.dart' as _i28;
import 'package:travel_aigent/models/ip_location_model.dart' as _i26;
import 'package:travel_aigent/models/plan_model.dart' as _i4;
import 'package:travel_aigent/models/preferences_model.dart' as _i20;
import 'package:travel_aigent/models/who_am_i_model.dart' as _i6;
import 'package:travel_aigent/services/admob_service.dart' as _i36;
import 'package:travel_aigent/services/ai_service.dart' as _i16;
import 'package:travel_aigent/services/airport_service.dart' as _i31;
import 'package:travel_aigent/services/analytics_service.dart' as _i23;
import 'package:travel_aigent/services/authentication_service.dart' as _i13;
import 'package:travel_aigent/services/average_price_service.dart' as _i30;
import 'package:travel_aigent/services/currency_scraper_service.dart' as _i27;
import 'package:travel_aigent/services/dio_service.dart' as _i7;
import 'package:travel_aigent/services/duck_duck_go_image_scraper_service/duck_duck_go_image_scraper_service.dart'
    as _i32;
import 'package:travel_aigent/services/firebase_user_service.dart' as _i24;
import 'package:travel_aigent/services/firestore_service.dart' as _i21;
import 'package:travel_aigent/services/generator_service.dart' as _i18;
import 'package:travel_aigent/services/hive_service.dart' as _i35;
import 'package:travel_aigent/services/ip_service.dart' as _i25;
import 'package:travel_aigent/services/trip_advisor_service.dart' as _i34;
import 'package:travel_aigent/services/web_scraper_service.dart' as _i14;
import 'package:travel_aigent/services/who_am_i_service.dart' as _i22;
import 'package:travel_aigent/services/wikipedia_scraper_service.dart' as _i29;
import 'package:uuid/uuid.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponse_0<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUuid_1 extends _i1.SmartFake implements _i3.Uuid {
  _FakeUuid_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePlan_2 extends _i1.SmartFake implements _i4.Plan {
  _FakePlan_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCollectionReference_3<T extends Object?> extends _i1.SmartFake
    implements _i5.CollectionReference<T> {
  _FakeCollectionReference_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWhoAmI_4 extends _i1.SmartFake implements _i6.WhoAmI {
  _FakeWhoAmI_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDioService_5 extends _i1.SmartFake implements _i7.DioService {
  _FakeDioService_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAirportData_6 extends _i1.SmartFake implements _i8.AirportData {
  _FakeAirportData_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NavigationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigationService extends _i1.Mock implements _i9.NavigationService {
  @override
  String get previousRoute => (super.noSuchMethod(
        Invocation.getter(#previousRoute),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  String get currentRoute => (super.noSuchMethod(
        Invocation.getter(#currentRoute),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  _i10.GlobalKey<_i10.NavigatorState>? nestedNavigationKey(int? index) =>
      (super.noSuchMethod(
        Invocation.method(
          #nestedNavigationKey,
          [index],
        ),
        returnValueForMissingStub: null,
      ) as _i10.GlobalKey<_i10.NavigatorState>?);
  @override
  void config({
    bool? enableLog,
    bool? defaultPopGesture,
    bool? defaultOpaqueRoute,
    Duration? defaultDurationTransition,
    bool? defaultGlobalState,
    _i9.Transition? defaultTransitionStyle,
    String? defaultTransition,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #config,
          [],
          {
            #enableLog: enableLog,
            #defaultPopGesture: defaultPopGesture,
            #defaultOpaqueRoute: defaultOpaqueRoute,
            #defaultDurationTransition: defaultDurationTransition,
            #defaultGlobalState: defaultGlobalState,
            #defaultTransitionStyle: defaultTransitionStyle,
            #defaultTransition: defaultTransition,
          },
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i11.Future<T?>? navigateWithTransition<T>(
    _i10.Widget? page, {
    bool? opaque,
    String? transition = r'',
    Duration? duration,
    bool? popGesture,
    int? id,
    _i10.Curve? curve,
    bool? fullscreenDialog = false,
    bool? preventDuplicates = true,
    _i9.Transition? transitionClass,
    _i9.Transition? transitionStyle,
    String? routeName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateWithTransition,
          [page],
          {
            #opaque: opaque,
            #transition: transition,
            #duration: duration,
            #popGesture: popGesture,
            #id: id,
            #curve: curve,
            #fullscreenDialog: fullscreenDialog,
            #preventDuplicates: preventDuplicates,
            #transitionClass: transitionClass,
            #transitionStyle: transitionStyle,
            #routeName: routeName,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i11.Future<T?>?);
  @override
  _i11.Future<T?>? replaceWithTransition<T>(
    _i10.Widget? page, {
    bool? opaque,
    String? transition = r'',
    Duration? duration,
    bool? popGesture,
    int? id,
    _i10.Curve? curve,
    bool? fullscreenDialog = false,
    bool? preventDuplicates = true,
    _i9.Transition? transitionClass,
    _i9.Transition? transitionStyle,
    String? routeName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceWithTransition,
          [page],
          {
            #opaque: opaque,
            #transition: transition,
            #duration: duration,
            #popGesture: popGesture,
            #id: id,
            #curve: curve,
            #fullscreenDialog: fullscreenDialog,
            #preventDuplicates: preventDuplicates,
            #transitionClass: transitionClass,
            #transitionStyle: transitionStyle,
            #routeName: routeName,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i11.Future<T?>?);
  @override
  bool back<T>({
    dynamic result,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #back,
          [],
          {
            #result: result,
            #id: id,
          },
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  void popUntil(
    _i10.RoutePredicate? predicate, {
    int? id,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #popUntil,
          [predicate],
          {#id: id},
        ),
        returnValueForMissingStub: null,
      );
  @override
  void popRepeated(int? popTimes) => super.noSuchMethod(
        Invocation.method(
          #popRepeated,
          [popTimes],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i11.Future<T?>? navigateTo<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    bool? preventDuplicates = true,
    Map<String, String>? parameters,
    _i10.RouteTransitionsBuilder? transition,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateTo,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #preventDuplicates: preventDuplicates,
            #parameters: parameters,
            #transition: transition,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i11.Future<T?>?);
  @override
  _i11.Future<T?>? navigateToView<T>(
    _i10.Widget? view, {
    dynamic arguments,
    int? id,
    bool? opaque,
    _i10.Curve? curve,
    Duration? duration,
    bool? fullscreenDialog = false,
    bool? popGesture,
    bool? preventDuplicates = true,
    _i9.Transition? transition,
    _i9.Transition? transitionStyle,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateToView,
          [view],
          {
            #arguments: arguments,
            #id: id,
            #opaque: opaque,
            #curve: curve,
            #duration: duration,
            #fullscreenDialog: fullscreenDialog,
            #popGesture: popGesture,
            #preventDuplicates: preventDuplicates,
            #transition: transition,
            #transitionStyle: transitionStyle,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i11.Future<T?>?);
  @override
  _i11.Future<T?>? replaceWith<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    bool? preventDuplicates = true,
    Map<String, String>? parameters,
    _i10.RouteTransitionsBuilder? transition,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceWith,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #preventDuplicates: preventDuplicates,
            #parameters: parameters,
            #transition: transition,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i11.Future<T?>?);
  @override
  _i11.Future<T?>? clearStackAndShow<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    Map<String, String>? parameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearStackAndShow,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #parameters: parameters,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i11.Future<T?>?);
  @override
  _i11.Future<T?>? clearStackAndShowView<T>(
    _i10.Widget? view, {
    dynamic arguments,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearStackAndShowView,
          [view],
          {
            #arguments: arguments,
            #id: id,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i11.Future<T?>?);
  @override
  _i11.Future<T?>? clearTillFirstAndShow<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    bool? preventDuplicates = true,
    Map<String, String>? parameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearTillFirstAndShow,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #preventDuplicates: preventDuplicates,
            #parameters: parameters,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i11.Future<T?>?);
  @override
  _i11.Future<T?>? clearTillFirstAndShowView<T>(
    _i10.Widget? view, {
    dynamic arguments,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearTillFirstAndShowView,
          [view],
          {
            #arguments: arguments,
            #id: id,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i11.Future<T?>?);
  @override
  _i11.Future<T?>? pushNamedAndRemoveUntil<T>(
    String? routeName, {
    _i10.RoutePredicate? predicate,
    dynamic arguments,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pushNamedAndRemoveUntil,
          [routeName],
          {
            #predicate: predicate,
            #arguments: arguments,
            #id: id,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i11.Future<T?>?);
}

/// A class which mocks [BottomSheetService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBottomSheetService extends _i1.Mock
    implements _i9.BottomSheetService {
  @override
  void setCustomSheetBuilders(Map<dynamic, _i9.SheetBuilder>? builders) =>
      super.noSuchMethod(
        Invocation.method(
          #setCustomSheetBuilders,
          [builders],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i11.Future<_i9.SheetResponse<dynamic>?> showBottomSheet({
    required String? title,
    String? description,
    String? confirmButtonTitle = r'Ok',
    String? cancelButtonTitle,
    bool? enableDrag = true,
    bool? barrierDismissible = true,
    bool? isScrollControlled = false,
    Duration? exitBottomSheetDuration,
    Duration? enterBottomSheetDuration,
    bool? ignoreSafeArea,
    bool? useRootNavigator = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showBottomSheet,
          [],
          {
            #title: title,
            #description: description,
            #confirmButtonTitle: confirmButtonTitle,
            #cancelButtonTitle: cancelButtonTitle,
            #enableDrag: enableDrag,
            #barrierDismissible: barrierDismissible,
            #isScrollControlled: isScrollControlled,
            #exitBottomSheetDuration: exitBottomSheetDuration,
            #enterBottomSheetDuration: enterBottomSheetDuration,
            #ignoreSafeArea: ignoreSafeArea,
            #useRootNavigator: useRootNavigator,
          },
        ),
        returnValue: _i11.Future<_i9.SheetResponse<dynamic>?>.value(),
        returnValueForMissingStub:
            _i11.Future<_i9.SheetResponse<dynamic>?>.value(),
      ) as _i11.Future<_i9.SheetResponse<dynamic>?>);
  @override
  _i11.Future<_i9.SheetResponse<T>?> showCustomSheet<T, R>({
    dynamic variant,
    String? title,
    String? description,
    bool? hasImage = false,
    String? imageUrl,
    bool? showIconInMainButton = false,
    String? mainButtonTitle,
    bool? showIconInSecondaryButton = false,
    String? secondaryButtonTitle,
    bool? showIconInAdditionalButton = false,
    String? additionalButtonTitle,
    bool? takesInput = false,
    _i12.Color? barrierColor = const _i12.Color(2315255808),
    bool? barrierDismissible = true,
    bool? isScrollControlled = false,
    String? barrierLabel = r'',
    dynamic customData,
    R? data,
    bool? enableDrag = true,
    Duration? exitBottomSheetDuration,
    Duration? enterBottomSheetDuration,
    bool? ignoreSafeArea,
    bool? useRootNavigator = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showCustomSheet,
          [],
          {
            #variant: variant,
            #title: title,
            #description: description,
            #hasImage: hasImage,
            #imageUrl: imageUrl,
            #showIconInMainButton: showIconInMainButton,
            #mainButtonTitle: mainButtonTitle,
            #showIconInSecondaryButton: showIconInSecondaryButton,
            #secondaryButtonTitle: secondaryButtonTitle,
            #showIconInAdditionalButton: showIconInAdditionalButton,
            #additionalButtonTitle: additionalButtonTitle,
            #takesInput: takesInput,
            #barrierColor: barrierColor,
            #barrierDismissible: barrierDismissible,
            #isScrollControlled: isScrollControlled,
            #barrierLabel: barrierLabel,
            #customData: customData,
            #data: data,
            #enableDrag: enableDrag,
            #exitBottomSheetDuration: exitBottomSheetDuration,
            #enterBottomSheetDuration: enterBottomSheetDuration,
            #ignoreSafeArea: ignoreSafeArea,
            #useRootNavigator: useRootNavigator,
          },
        ),
        returnValue: _i11.Future<_i9.SheetResponse<T>?>.value(),
        returnValueForMissingStub: _i11.Future<_i9.SheetResponse<T>?>.value(),
      ) as _i11.Future<_i9.SheetResponse<T>?>);
  @override
  void completeSheet(_i9.SheetResponse<dynamic>? response) =>
      super.noSuchMethod(
        Invocation.method(
          #completeSheet,
          [response],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [DialogService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDialogService extends _i1.Mock implements _i9.DialogService {
  @override
  void registerCustomDialogBuilders(
          Map<dynamic, _i9.DialogBuilder>? builders) =>
      super.noSuchMethod(
        Invocation.method(
          #registerCustomDialogBuilders,
          [builders],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void registerCustomDialogBuilder({
    required dynamic variant,
    required _i10.Widget Function(
      _i10.BuildContext,
      _i9.DialogRequest<dynamic>,
      dynamic Function(_i9.DialogResponse<dynamic>),
    )? builder,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #registerCustomDialogBuilder,
          [],
          {
            #variant: variant,
            #builder: builder,
          },
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i11.Future<_i9.DialogResponse<dynamic>?> showDialog({
    String? title,
    String? description,
    String? cancelTitle,
    _i12.Color? cancelTitleColor,
    String? buttonTitle = r'Ok',
    _i12.Color? buttonTitleColor,
    bool? barrierDismissible = false,
    _i9.DialogPlatform? dialogPlatform,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showDialog,
          [],
          {
            #title: title,
            #description: description,
            #cancelTitle: cancelTitle,
            #cancelTitleColor: cancelTitleColor,
            #buttonTitle: buttonTitle,
            #buttonTitleColor: buttonTitleColor,
            #barrierDismissible: barrierDismissible,
            #dialogPlatform: dialogPlatform,
          },
        ),
        returnValue: _i11.Future<_i9.DialogResponse<dynamic>?>.value(),
        returnValueForMissingStub:
            _i11.Future<_i9.DialogResponse<dynamic>?>.value(),
      ) as _i11.Future<_i9.DialogResponse<dynamic>?>);
  @override
  _i11.Future<_i9.DialogResponse<T>?> showCustomDialog<T, R>({
    dynamic variant,
    String? title,
    String? description,
    bool? hasImage = false,
    String? imageUrl,
    bool? showIconInMainButton = false,
    String? mainButtonTitle,
    bool? showIconInSecondaryButton = false,
    String? secondaryButtonTitle,
    bool? showIconInAdditionalButton = false,
    String? additionalButtonTitle,
    bool? takesInput = false,
    _i12.Color? barrierColor = const _i12.Color(2315255808),
    bool? barrierDismissible = false,
    String? barrierLabel = r'',
    bool? useSafeArea = true,
    dynamic customData,
    R? data,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showCustomDialog,
          [],
          {
            #variant: variant,
            #title: title,
            #description: description,
            #hasImage: hasImage,
            #imageUrl: imageUrl,
            #showIconInMainButton: showIconInMainButton,
            #mainButtonTitle: mainButtonTitle,
            #showIconInSecondaryButton: showIconInSecondaryButton,
            #secondaryButtonTitle: secondaryButtonTitle,
            #showIconInAdditionalButton: showIconInAdditionalButton,
            #additionalButtonTitle: additionalButtonTitle,
            #takesInput: takesInput,
            #barrierColor: barrierColor,
            #barrierDismissible: barrierDismissible,
            #barrierLabel: barrierLabel,
            #useSafeArea: useSafeArea,
            #customData: customData,
            #data: data,
          },
        ),
        returnValue: _i11.Future<_i9.DialogResponse<T>?>.value(),
        returnValueForMissingStub: _i11.Future<_i9.DialogResponse<T>?>.value(),
      ) as _i11.Future<_i9.DialogResponse<T>?>);
  @override
  _i11.Future<_i9.DialogResponse<dynamic>?> showConfirmationDialog({
    String? title,
    String? description,
    String? cancelTitle = r'Cancel',
    _i12.Color? cancelTitleColor,
    String? confirmationTitle = r'Ok',
    _i12.Color? confirmationTitleColor,
    bool? barrierDismissible = false,
    _i9.DialogPlatform? dialogPlatform,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showConfirmationDialog,
          [],
          {
            #title: title,
            #description: description,
            #cancelTitle: cancelTitle,
            #cancelTitleColor: cancelTitleColor,
            #confirmationTitle: confirmationTitle,
            #confirmationTitleColor: confirmationTitleColor,
            #barrierDismissible: barrierDismissible,
            #dialogPlatform: dialogPlatform,
          },
        ),
        returnValue: _i11.Future<_i9.DialogResponse<dynamic>?>.value(),
        returnValueForMissingStub:
            _i11.Future<_i9.DialogResponse<dynamic>?>.value(),
      ) as _i11.Future<_i9.DialogResponse<dynamic>?>);
  @override
  void completeDialog(_i9.DialogResponse<dynamic>? response) =>
      super.noSuchMethod(
        Invocation.method(
          #completeDialog,
          [response],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AuthenticationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationService extends _i1.Mock
    implements _i13.AuthenticationService {
  @override
  _i11.Future<void> createAnonymousUser() => (super.noSuchMethod(
        Invocation.method(
          #createAnonymousUser,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  _i11.Future<String?> linkUserWithEmailCredential(
    String? name,
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #linkUserWithEmailCredential,
          [
            name,
            email,
            password,
          ],
        ),
        returnValue: _i11.Future<String?>.value(),
        returnValueForMissingStub: _i11.Future<String?>.value(),
      ) as _i11.Future<String?>);
  @override
  _i11.Future<String?> signInWithEmailAndPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithEmailAndPassword,
          [
            email,
            password,
          ],
        ),
        returnValue: _i11.Future<String?>.value(),
        returnValueForMissingStub: _i11.Future<String?>.value(),
      ) as _i11.Future<String?>);
  @override
  _i11.Future<String?> reauthenticateWithCredential(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #reauthenticateWithCredential,
          [
            email,
            password,
          ],
        ),
        returnValue: _i11.Future<String?>.value(),
        returnValueForMissingStub: _i11.Future<String?>.value(),
      ) as _i11.Future<String?>);
}

/// A class which mocks [DioService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDioService extends _i1.Mock implements _i7.DioService {
  @override
  _i11.Future<_i2.Response<dynamic>> get(
    String? url, {
    Map<String, dynamic>? parameters,
    Map<String, dynamic>? headers,
    bool? printResponse = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {
            #parameters: parameters,
            #headers: headers,
            #printResponse: printResponse,
          },
        ),
        returnValue:
            _i11.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
          this,
          Invocation.method(
            #get,
            [url],
            {
              #parameters: parameters,
              #headers: headers,
              #printResponse: printResponse,
            },
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
          this,
          Invocation.method(
            #get,
            [url],
            {
              #parameters: parameters,
              #headers: headers,
              #printResponse: printResponse,
            },
          ),
        )),
      ) as _i11.Future<_i2.Response<dynamic>>);
  @override
  _i11.Future<_i2.Response<dynamic>> post(
    String? url, {
    Map<String, dynamic>? parameters,
    Map<String, dynamic>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #parameters: parameters,
            #headers: headers,
          },
        ),
        returnValue:
            _i11.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #parameters: parameters,
              #headers: headers,
            },
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #parameters: parameters,
              #headers: headers,
            },
          ),
        )),
      ) as _i11.Future<_i2.Response<dynamic>>);
  @override
  _i11.Future<_i2.Response<dynamic>> put(
    String? url, {
    Map<String, dynamic>? parameters,
    Map<String, dynamic>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #parameters: parameters,
            #headers: headers,
          },
        ),
        returnValue:
            _i11.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #parameters: parameters,
              #headers: headers,
            },
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #parameters: parameters,
              #headers: headers,
            },
          ),
        )),
      ) as _i11.Future<_i2.Response<dynamic>>);
  @override
  _i11.Future<_i2.Response<dynamic>> patch(
    String? url, {
    Map<String, dynamic>? parameters,
    Map<String, dynamic>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #parameters: parameters,
            #headers: headers,
          },
        ),
        returnValue:
            _i11.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #parameters: parameters,
              #headers: headers,
            },
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #parameters: parameters,
              #headers: headers,
            },
          ),
        )),
      ) as _i11.Future<_i2.Response<dynamic>>);
}

/// A class which mocks [WebScraperService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebScraperService extends _i1.Mock implements _i14.WebScraperService {
  @override
  _i11.Future<_i15.BeautifulSoup?> fetchBeautifulSoup(String? url) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchBeautifulSoup,
          [url],
        ),
        returnValue: _i11.Future<_i15.BeautifulSoup?>.value(),
        returnValueForMissingStub: _i11.Future<_i15.BeautifulSoup?>.value(),
      ) as _i11.Future<_i15.BeautifulSoup?>);
  @override
  double? sanitisePrice(
    String? str, {
    int? decimalPlaces = 2,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sanitisePrice,
          [str],
          {#decimalPlaces: decimalPlaces},
        ),
        returnValueForMissingStub: null,
      ) as double?);
}

/// A class which mocks [AiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAiService extends _i1.Mock implements _i16.AiService {
  @override
  _i11.Future<String> request(
    String? prompt,
    int? maxTokens, {
    List<_i17.OpenAIFunctionModel>? functions,
    _i17.FunctionCall? functionCall = _i17.FunctionCall.none,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #request,
          [
            prompt,
            maxTokens,
          ],
          {
            #functions: functions,
            #functionCall: functionCall,
          },
        ),
        returnValue: _i11.Future<String>.value(''),
        returnValueForMissingStub: _i11.Future<String>.value(''),
      ) as _i11.Future<String>);
}

/// A class which mocks [GeneratorService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGeneratorService extends _i1.Mock implements _i18.GeneratorService {
  @override
  _i3.Uuid get uuid => (super.noSuchMethod(
        Invocation.getter(#uuid),
        returnValue: _FakeUuid_1(
          this,
          Invocation.getter(#uuid),
        ),
        returnValueForMissingStub: _FakeUuid_1(
          this,
          Invocation.getter(#uuid),
        ),
      ) as _i3.Uuid);
  @override
  void setDestination(_i19.Destination? destination) => super.noSuchMethod(
        Invocation.method(
          #setDestination,
          [destination],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void setPreferences(_i20.Preferences? preferences) => super.noSuchMethod(
        Invocation.method(
          #setPreferences,
          [preferences],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addToBlacklistedCities(String? city) => super.noSuchMethod(
        Invocation.method(
          #addToBlacklistedCities,
          [city],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void clearBlackList() => super.noSuchMethod(
        Invocation.method(
          #clearBlackList,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i11.Future<_i4.Plan> generatePlan() => (super.noSuchMethod(
        Invocation.method(
          #generatePlan,
          [],
        ),
        returnValue: _i11.Future<_i4.Plan>.value(_FakePlan_2(
          this,
          Invocation.method(
            #generatePlan,
            [],
          ),
        )),
        returnValueForMissingStub: _i11.Future<_i4.Plan>.value(_FakePlan_2(
          this,
          Invocation.method(
            #generatePlan,
            [],
          ),
        )),
      ) as _i11.Future<_i4.Plan>);
  @override
  _i11.Future<_i4.Plan> fetchImages(_i4.Plan? plan) => (super.noSuchMethod(
        Invocation.method(
          #fetchImages,
          [plan],
        ),
        returnValue: _i11.Future<_i4.Plan>.value(_FakePlan_2(
          this,
          Invocation.method(
            #fetchImages,
            [plan],
          ),
        )),
        returnValueForMissingStub: _i11.Future<_i4.Plan>.value(_FakePlan_2(
          this,
          Invocation.method(
            #fetchImages,
            [plan],
          ),
        )),
      ) as _i11.Future<_i4.Plan>);
}

/// A class which mocks [FirestoreService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreService extends _i1.Mock implements _i21.FirestoreService {
  @override
  _i5.CollectionReference<Object?> get usersCollection => (super.noSuchMethod(
        Invocation.getter(#usersCollection),
        returnValue: _FakeCollectionReference_3<Object?>(
          this,
          Invocation.getter(#usersCollection),
        ),
        returnValueForMissingStub: _FakeCollectionReference_3<Object?>(
          this,
          Invocation.getter(#usersCollection),
        ),
      ) as _i5.CollectionReference<Object?>);
  @override
  _i5.CollectionReference<Object?> get plansCollection => (super.noSuchMethod(
        Invocation.getter(#plansCollection),
        returnValue: _FakeCollectionReference_3<Object?>(
          this,
          Invocation.getter(#plansCollection),
        ),
        returnValueForMissingStub: _FakeCollectionReference_3<Object?>(
          this,
          Invocation.getter(#plansCollection),
        ),
      ) as _i5.CollectionReference<Object?>);
  @override
  _i11.Future<void> setMeasurementSystem(
    String? userId,
    _i6.MeasurementSystem? system,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setMeasurementSystem,
          [
            userId,
            system,
          ],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  _i11.Future<bool> addUser(
    String? userId,
    String? name,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addUser,
          [
            userId,
            name,
          ],
        ),
        returnValue: _i11.Future<bool>.value(false),
        returnValueForMissingStub: _i11.Future<bool>.value(false),
      ) as _i11.Future<bool>);
  @override
  _i11.Future<bool> getUser() => (super.noSuchMethod(
        Invocation.method(
          #getUser,
          [],
        ),
        returnValue: _i11.Future<bool>.value(false),
        returnValueForMissingStub: _i11.Future<bool>.value(false),
      ) as _i11.Future<bool>);
  @override
  _i11.Future<bool> addPlan(_i4.Plan? plan) => (super.noSuchMethod(
        Invocation.method(
          #addPlan,
          [plan],
        ),
        returnValue: _i11.Future<bool>.value(false),
        returnValueForMissingStub: _i11.Future<bool>.value(false),
      ) as _i11.Future<bool>);
  @override
  _i11.Future<bool> updateUserName(
    String? userId,
    String? name,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserName,
          [
            userId,
            name,
          ],
        ),
        returnValue: _i11.Future<bool>.value(false),
        returnValueForMissingStub: _i11.Future<bool>.value(false),
      ) as _i11.Future<bool>);
  @override
  _i11.Future<bool> deleteUserCollection(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #deleteUserCollection,
          [userId],
        ),
        returnValue: _i11.Future<bool>.value(false),
        returnValueForMissingStub: _i11.Future<bool>.value(false),
      ) as _i11.Future<bool>);
  @override
  _i11.Future<bool> deleteUserPlanCollection(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteUserPlanCollection,
          [userId],
        ),
        returnValue: _i11.Future<bool>.value(false),
        returnValueForMissingStub: _i11.Future<bool>.value(false),
      ) as _i11.Future<bool>);
}

/// A class which mocks [WhoAmIService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWhoAmIService extends _i1.Mock implements _i22.WhoAmIService {
  @override
  _i6.WhoAmI get whoAmI => (super.noSuchMethod(
        Invocation.getter(#whoAmI),
        returnValue: _FakeWhoAmI_4(
          this,
          Invocation.getter(#whoAmI),
        ),
        returnValueForMissingStub: _FakeWhoAmI_4(
          this,
          Invocation.getter(#whoAmI),
        ),
      ) as _i6.WhoAmI);
  @override
  set whoAmI(_i6.WhoAmI? _whoAmI) => super.noSuchMethod(
        Invocation.setter(
          #whoAmI,
          _whoAmI,
        ),
        returnValueForMissingStub: null,
      );
  @override
  int get listenersCount => (super.noSuchMethod(
        Invocation.getter(#listenersCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);
  @override
  void setName(String? name) => super.noSuchMethod(
        Invocation.method(
          #setName,
          [name],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void setWhoAmI(Map<String, dynamic>? data) => super.noSuchMethod(
        Invocation.method(
          #setWhoAmI,
          [data],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addPlan(_i4.Plan? plan) => super.noSuchMethod(
        Invocation.method(
          #addPlan,
          [plan],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void reset() => super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) =>
      super.noSuchMethod(
        Invocation.method(
          #listenToReactiveValues,
          [reactiveValues],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void removeListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AnalyticsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsService extends _i1.Mock implements _i23.AnalyticsService {
  @override
  void logEvent(
    String? name, {
    Map<String, dynamic>? parameters,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #logEvent,
          [name],
          {#parameters: parameters},
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [FirebaseUserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseUserService extends _i1.Mock
    implements _i24.FirebaseUserService {
  @override
  void init() => super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool isFullUser() => (super.noSuchMethod(
        Invocation.method(
          #isFullUser,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  bool isUserLoggedIn() => (super.noSuchMethod(
        Invocation.method(
          #isUserLoggedIn,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  bool isAnonymousUser() => (super.noSuchMethod(
        Invocation.method(
          #isAnonymousUser,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  _i11.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  _i11.Future<String?> deleteUser() => (super.noSuchMethod(
        Invocation.method(
          #deleteUser,
          [],
        ),
        returnValue: _i11.Future<String?>.value(),
        returnValueForMissingStub: _i11.Future<String?>.value(),
      ) as _i11.Future<String?>);
}

/// A class which mocks [IpService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIpService extends _i1.Mock implements _i25.IpService {
  @override
  set ipLocation(_i26.IpLocation? _ipLocation) => super.noSuchMethod(
        Invocation.setter(
          #ipLocation,
          _ipLocation,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i11.Future<_i26.IpLocation?> getUserLocation() => (super.noSuchMethod(
        Invocation.method(
          #getUserLocation,
          [],
        ),
        returnValue: _i11.Future<_i26.IpLocation?>.value(),
        returnValueForMissingStub: _i11.Future<_i26.IpLocation?>.value(),
      ) as _i11.Future<_i26.IpLocation?>);
}

/// A class which mocks [CurrencyScraperService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCurrencyScraperService extends _i1.Mock
    implements _i27.CurrencyScraperService {
  @override
  _i11.Future<_i28.ExchangeRateData?> fetchExchangeRateData(
    String? city,
    String? country,
    String? fromCurrency,
    String? toCurrency,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchExchangeRateData,
          [
            city,
            country,
            fromCurrency,
            toCurrency,
          ],
        ),
        returnValue: _i11.Future<_i28.ExchangeRateData?>.value(),
        returnValueForMissingStub: _i11.Future<_i28.ExchangeRateData?>.value(),
      ) as _i11.Future<_i28.ExchangeRateData?>);
}

/// A class which mocks [WikipediaScraperService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWikipediaScraperService extends _i1.Mock
    implements _i29.WikipediaScraperService {
  @override
  _i11.Future<String?> getImage(String? query) => (super.noSuchMethod(
        Invocation.method(
          #getImage,
          [query],
        ),
        returnValue: _i11.Future<String?>.value(),
        returnValueForMissingStub: _i11.Future<String?>.value(),
      ) as _i11.Future<String?>);
  @override
  _i11.Future<String> getWikipediaImageSmall(String? searchTerm) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWikipediaImageSmall,
          [searchTerm],
        ),
        returnValue: _i11.Future<String>.value(''),
        returnValueForMissingStub: _i11.Future<String>.value(''),
      ) as _i11.Future<String>);
  @override
  _i11.Future<String> getWikipediaImageLarge(String? searchTerm) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWikipediaImageLarge,
          [searchTerm],
        ),
        returnValue: _i11.Future<String>.value(''),
        returnValueForMissingStub: _i11.Future<String>.value(''),
      ) as _i11.Future<String>);
}

/// A class which mocks [AveragePriceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAveragePriceService extends _i1.Mock
    implements _i30.AveragePriceService {
  @override
  _i7.DioService get dioService => (super.noSuchMethod(
        Invocation.getter(#dioService),
        returnValue: _FakeDioService_5(
          this,
          Invocation.getter(#dioService),
        ),
        returnValueForMissingStub: _FakeDioService_5(
          this,
          Invocation.getter(#dioService),
        ),
      ) as _i7.DioService);
  @override
  _i11.Future<Map<String, dynamic>?> fetchAveragePrices(
    String? city,
    String? country,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchAveragePrices,
          [
            city,
            country,
          ],
        ),
        returnValue: _i11.Future<Map<String, dynamic>?>.value(),
        returnValueForMissingStub: _i11.Future<Map<String, dynamic>?>.value(),
      ) as _i11.Future<Map<String, dynamic>?>);
}

/// A class which mocks [AirportService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAirportService extends _i1.Mock implements _i31.AirportService {
  @override
  _i8.AirportData get airportData => (super.noSuchMethod(
        Invocation.getter(#airportData),
        returnValue: _FakeAirportData_6(
          this,
          Invocation.getter(#airportData),
        ),
        returnValueForMissingStub: _FakeAirportData_6(
          this,
          Invocation.getter(#airportData),
        ),
      ) as _i8.AirportData);
  @override
  set airportData(_i8.AirportData? _airportData) => super.noSuchMethod(
        Invocation.setter(
          #airportData,
          _airportData,
        ),
        returnValueForMissingStub: null,
      );
  @override
  String get defaultFromValue => (super.noSuchMethod(
        Invocation.getter(#defaultFromValue),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  set defaultFromValue(String? _defaultFromValue) => super.noSuchMethod(
        Invocation.setter(
          #defaultFromValue,
          _defaultFromValue,
        ),
        returnValueForMissingStub: null,
      );
  @override
  void getDefaultFromValue() => super.noSuchMethod(
        Invocation.method(
          #getDefaultFromValue,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i11.Future<void> loadAirports() => (super.noSuchMethod(
        Invocation.method(
          #loadAirports,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
}

/// A class which mocks [DuckDuckGoImageScraperService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDuckDuckGoImageScraperService extends _i1.Mock
    implements _i32.DuckDuckGoImageScraperService {
  @override
  _i11.Future<List<_i33.DuckWebImage>> getImages(
    String? query, {
    int? imagesToReturn = 5,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getImages,
          [query],
          {#imagesToReturn: imagesToReturn},
        ),
        returnValue:
            _i11.Future<List<_i33.DuckWebImage>>.value(<_i33.DuckWebImage>[]),
        returnValueForMissingStub:
            _i11.Future<List<_i33.DuckWebImage>>.value(<_i33.DuckWebImage>[]),
      ) as _i11.Future<List<_i33.DuckWebImage>>);
}

/// A class which mocks [TripAdvisorService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTripAdvisorService extends _i1.Mock
    implements _i34.TripAdvisorService {}

/// A class which mocks [HiveService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHiveService extends _i1.Mock implements _i35.HiveService {
  @override
  _i11.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  _i11.Future<void> write(
    String? key,
    dynamic value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #write,
          [
            key,
            value,
          ],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  _i11.Future<dynamic> read(String? key) => (super.noSuchMethod(
        Invocation.method(
          #read,
          [key],
        ),
        returnValue: _i11.Future<dynamic>.value(),
        returnValueForMissingStub: _i11.Future<dynamic>.value(),
      ) as _i11.Future<dynamic>);
  @override
  _i11.Future<void> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
}

/// A class which mocks [AdmobService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdmobService extends _i1.Mock implements _i36.AdmobService {
  @override
  set generatePlanBannerAd(_i37.BannerAd? _generatePlanBannerAd) =>
      super.noSuchMethod(
        Invocation.setter(
          #generatePlanBannerAd,
          _generatePlanBannerAd,
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool get generatePlanBannerAdisLoaded => (super.noSuchMethod(
        Invocation.getter(#generatePlanBannerAdisLoaded),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  set generatePlanBannerAdisLoaded(bool? _generatePlanBannerAdisLoaded) =>
      super.noSuchMethod(
        Invocation.setter(
          #generatePlanBannerAdisLoaded,
          _generatePlanBannerAdisLoaded,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set afterSavePlanInterstitialAd(
          _i37.InterstitialAd? _afterSavePlanInterstitialAd) =>
      super.noSuchMethod(
        Invocation.setter(
          #afterSavePlanInterstitialAd,
          _afterSavePlanInterstitialAd,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set appOpenAd(_i37.AppOpenAd? _appOpenAd) => super.noSuchMethod(
        Invocation.setter(
          #appOpenAd,
          _appOpenAd,
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool get isShowingAppOpenAd => (super.noSuchMethod(
        Invocation.getter(#isShowingAppOpenAd),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  set isShowingAppOpenAd(bool? _isShowingAppOpenAd) => super.noSuchMethod(
        Invocation.setter(
          #isShowingAppOpenAd,
          _isShowingAppOpenAd,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set planViewNativeAd(_i37.NativeAd? _planViewNativeAd) => super.noSuchMethod(
        Invocation.setter(
          #planViewNativeAd,
          _planViewNativeAd,
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool get planViewNativeAdIsLoaded => (super.noSuchMethod(
        Invocation.getter(#planViewNativeAdIsLoaded),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  set planViewNativeAdIsLoaded(bool? _planViewNativeAdIsLoaded) =>
      super.noSuchMethod(
        Invocation.setter(
          #planViewNativeAdIsLoaded,
          _planViewNativeAdIsLoaded,
        ),
        returnValueForMissingStub: null,
      );
  @override
  String get loadingPlanBannerAdId => (super.noSuchMethod(
        Invocation.getter(#loadingPlanBannerAdId),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  String get afterSavePlanInterstitialAdId => (super.noSuchMethod(
        Invocation.getter(#afterSavePlanInterstitialAdId),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  String get appOpenAdId => (super.noSuchMethod(
        Invocation.getter(#appOpenAdId),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  String get planViewNativeAdId => (super.noSuchMethod(
        Invocation.getter(#planViewNativeAdId),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  bool get isAppOpenAdAvailable => (super.noSuchMethod(
        Invocation.getter(#isAppOpenAdAvailable),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  _i11.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  dynamic loadGeneratePlanBannerAd({required Function? onAdLoadedCallback}) =>
      super.noSuchMethod(
        Invocation.method(
          #loadGeneratePlanBannerAd,
          [],
          {#onAdLoadedCallback: onAdLoadedCallback},
        ),
        returnValueForMissingStub: null,
      );
  @override
  void loadAfterSavePlanInterstitialAd() => super.noSuchMethod(
        Invocation.method(
          #loadAfterSavePlanInterstitialAd,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void loadPlanViewNativeAd({required Function? onAdLoadedCallback}) =>
      super.noSuchMethod(
        Invocation.method(
          #loadPlanViewNativeAd,
          [],
          {#onAdLoadedCallback: onAdLoadedCallback},
        ),
        returnValueForMissingStub: null,
      );
  @override
  void loadAppOpenAd() => super.noSuchMethod(
        Invocation.method(
          #loadAppOpenAd,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void showAppOpenAdIfAvailable() => super.noSuchMethod(
        Invocation.method(
          #showAppOpenAdIfAvailable,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
